/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    news: News;
    teams: Team;
    players: Player;
    coaches: Coach;
    sponsors: Sponsor;
    opponents: Opponent;
    matches: Match;
    people: Person;
    'team-lineups': TeamLineup;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    coaches: CoachesSelect<false> | CoachesSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    opponents: OpponentsSelect<false> | OpponentsSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    'team-lineups': TeamLineupsSelect<false> | TeamLineupsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    nav: Nav;
    footer: Footer;
    logo: Logo;
    'club-arenas': ClubArena;
  };
  globalsSelect: {
    nav: NavSelect<false> | NavSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    logo: LogoSelect<false> | LogoSelect<true>;
    'club-arenas': ClubArenasSelect<false> | ClubArenasSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  /**
   * Used to organize images in the media library
   */
  folder: 'teams' | 'players' | 'coaches' | 'volunteer' | 'sponsors' | 'opponents' | 'news' | 'general';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * URL slug (t.ex. "home", "about")
   */
  slug: string;
  layout?:
    | (
        | {
            title?: string | null;
            body?: string | null;
            image?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title: string;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'list-block';
          }
        | {
            title: string;
            backgroundColor?: ('black' | 'white' | 'primary-500' | 'secondary-500' | 'tertiary-500') | null;
            textColor?: ('black' | 'white') | null;
            fullwidth?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'banner';
          }
        | {
            title: string;
            body?: string | null;
            image: string | Media;
            layout?: {
              contentAlignment?: ('tleft' | 'center' | 'right') | null;
              height?: ('small' | 'medium' | 'large' | 'xlarge') | null;
              overlayIntensity?: ('light' | 'medium' | 'dark' | 'none') | null;
            };
            button?: {
              showButton?: boolean | null;
              buttonText?: string | null;
              buttonLink?: string | null;
              buttonStyle?: ('primary' | 'secondary' | 'outline') | null;
              buttonPosition?: ('below' | 'inline') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'test';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'sponsors';
          }
        | {
            title?: string | null;
            undertitle?: string | null;
            body?: string | null;
            image?: (string | null) | Media;
            link: {
              linkType?: ('internal' | 'external') | null;
              internal?:
                | ({
                    relationTo: 'pages';
                    value: string | Page;
                  } | null)
                | ({
                    relationTo: 'news';
                    value: string | News;
                  } | null);
              external?: string | null;
              text: string;
            };
            fullwidth?: boolean | null;
            imageLeft?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageTextBlock';
          }
        | {
            title?: string | null;
            undertitle?: string | null;
            body?: string | null;
            image?: (string | null) | Media;
            link: {
              linkType?: ('internal' | 'external') | null;
              internal?:
                | ({
                    relationTo: 'pages';
                    value: string | Page;
                  } | null)
                | ({
                    relationTo: 'news';
                    value: string | News;
                  } | null);
              external?: string | null;
              text: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  title: string;
  /**
   * Underrubrik som visas under titeln
   */
  subtitle?: string | null;
  /**
   * inledning visas i nyhetskortet
   */
  intro?: string | null;
  /**
   * text till knappen
   */
  buttonText?: string | null;
  slug: string;
  content: (
    | {
        subtitle?: string | null;
        text: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'textBlock';
      }
    | {
        image: string | Media;
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'imageBlock';
      }
  )[];
  image?: (string | null) | Media;
  checklist?:
    | {
        title: string;
        items: {
          title: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  author: {
    authorType: 'person' | 'manual';
    person?: (string | null) | Person;
    manualName?: string | null;
  };
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: string;
  forename: string;
  lastName: string;
  fullName?: string | null;
  role:
    | 'chairman'
    | 'vice-chairman'
    | 'secretary'
    | 'treasurer'
    | 'member'
    | 'substitute'
    | 'player-manager'
    | 'editor';
  responsibility?: ('children' | 'junior' | 'senior') | null;
  email: string;
  phone?: string | null;
  image?: (string | null) | Media;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: string;
  name: string;
  category: 'men' | 'women';
  season: '2025/2026';
  league: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: string;
  forename: string;
  lastname: string;
  fullName?: string | null;
  slug: string;
  dateOfBirth: string;
  position: 'back' | 'forward' | 'center' | 'goalie';
  stickSide?: ('left' | 'right' | 'none') | null;
  jerseyNumber: number;
  images: {
    profile: string | Media;
    portrait: string | Media;
  };
  team: string | Team;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches".
 */
export interface Coach {
  id: string;
  forename: string;
  lastname: string;
  fullName?: string | null;
  role: 'head-coach' | 'assistant-coach' | 'equipment-manager';
  email: string;
  phone?: string | null;
  image?: (string | null) | Media;
  team: string | Team;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: string;
  name: string;
  logo?: (string | null) | Media;
  website: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opponents".
 */
export interface Opponent {
  id: string;
  name: string;
  logo?: (string | null) | Media;
  category: 'men' | 'women';
  city?: string | null;
  homeArena?: string | null;
  arenaAddress?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: string;
  date: string;
  round: number;
  team: string | Team;
  opponent: string | Opponent;
  isHomeGame: boolean;
  teamScore?: number | null;
  opponentScore?: number | null;
  isFinished?: boolean | null;
  goals?:
    | {
        period: 'p1' | 'p2' | 'p3' | 'ot' | 'so';
        minute: string;
        teamType: 'own' | 'opponent';
        scorer?: (string | null) | Player;
        scorerName?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-lineups".
 */
export interface TeamLineup {
  id: string;
  /**
   * Ex: Herrar 2025/26 – Lagbild
   */
  title: string;
  team: string | Team;
  season: string;
  image: string | Media;
  hotspots?:
    | {
        player: string | Player;
        x: number;
        y: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'news';
        value: string | News;
      } | null)
    | ({
        relationTo: 'teams';
        value: string | Team;
      } | null)
    | ({
        relationTo: 'players';
        value: string | Player;
      } | null)
    | ({
        relationTo: 'coaches';
        value: string | Coach;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: string | Sponsor;
      } | null)
    | ({
        relationTo: 'opponents';
        value: string | Opponent;
      } | null)
    | ({
        relationTo: 'matches';
        value: string | Match;
      } | null)
    | ({
        relationTo: 'people';
        value: string | Person;
      } | null)
    | ({
        relationTo: 'team-lineups';
        value: string | TeamLineup;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              body?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        'list-block'?:
          | T
          | {
              title?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        banner?:
          | T
          | {
              title?: T;
              backgroundColor?: T;
              textColor?: T;
              fullwidth?: T;
              id?: T;
              blockName?: T;
            };
        test?:
          | T
          | {
              title?: T;
              body?: T;
              image?: T;
              layout?:
                | T
                | {
                    contentAlignment?: T;
                    height?: T;
                    overlayIntensity?: T;
                  };
              button?:
                | T
                | {
                    showButton?: T;
                    buttonText?: T;
                    buttonLink?: T;
                    buttonStyle?: T;
                    buttonPosition?: T;
                  };
              id?: T;
              blockName?: T;
            };
        sponsors?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        imageTextBlock?:
          | T
          | {
              title?: T;
              undertitle?: T;
              body?: T;
              image?: T;
              link?:
                | T
                | {
                    linkType?: T;
                    internal?: T;
                    external?: T;
                    text?: T;
                  };
              fullwidth?: T;
              imageLeft?: T;
              id?: T;
              blockName?: T;
            };
        newsBlock?:
          | T
          | {
              title?: T;
              undertitle?: T;
              body?: T;
              image?: T;
              link?:
                | T
                | {
                    linkType?: T;
                    internal?: T;
                    external?: T;
                    text?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  intro?: T;
  buttonText?: T;
  slug?: T;
  content?:
    | T
    | {
        textBlock?:
          | T
          | {
              subtitle?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        imageBlock?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  image?: T;
  checklist?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              title?: T;
              id?: T;
            };
        id?: T;
      };
  author?:
    | T
    | {
        authorType?: T;
        person?: T;
        manualName?: T;
      };
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  season?: T;
  league?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  forename?: T;
  lastname?: T;
  fullName?: T;
  slug?: T;
  dateOfBirth?: T;
  position?: T;
  stickSide?: T;
  jerseyNumber?: T;
  images?:
    | T
    | {
        profile?: T;
        portrait?: T;
      };
  team?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches_select".
 */
export interface CoachesSelect<T extends boolean = true> {
  forename?: T;
  lastname?: T;
  fullName?: T;
  role?: T;
  email?: T;
  phone?: T;
  image?: T;
  team?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opponents_select".
 */
export interface OpponentsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  category?: T;
  city?: T;
  homeArena?: T;
  arenaAddress?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  date?: T;
  round?: T;
  team?: T;
  opponent?: T;
  isHomeGame?: T;
  teamScore?: T;
  opponentScore?: T;
  isFinished?: T;
  goals?:
    | T
    | {
        period?: T;
        minute?: T;
        teamType?: T;
        scorer?: T;
        scorerName?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  forename?: T;
  lastName?: T;
  fullName?: T;
  role?: T;
  responsibility?: T;
  email?: T;
  phone?: T;
  image?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-lineups_select".
 */
export interface TeamLineupsSelect<T extends boolean = true> {
  title?: T;
  team?: T;
  season?: T;
  image?: T;
  hotspots?:
    | T
    | {
        player?: T;
        x?: T;
        y?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav".
 */
export interface Nav {
  id: string;
  items: {
    type: 'internal' | 'dropdown';
    /**
     * Text som visas i navigationen
     */
    label: string;
    /**
     * Välj en intern sida
     */
    page?: (string | null) | Page;
    /**
     * Valfri ikon (kan användas med Phosphor Icons)
     */
    icon?: ('none' | 'home' | 'user' | 'settings' | 'book' | 'star') | null;
    /**
     * Undermeny-items för dropdown
     */
    subItems?:
      | {
          label: string;
          page: string | Page;
          /**
           * Kort beskrivning (visas under länken)
           */
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Framhäv denna länk (t.ex. CTA-knapp)
     */
    highlighted?: boolean | null;
    /**
     * Visa i mobil-navigation
     */
    showOnMobile?: boolean | null;
    /**
     * Kräver inloggning för att visa
     */
    requiresAuth?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Logo för navigationen
   */
  logo?: (string | null) | Media;
  ctaButton?: {
    enabled?: boolean | null;
    label?: string | null;
    link?: string | null;
    style?: ('primary' | 'secondary' | 'outline') | null;
  };
  socialLinks?: {
    enabled?: boolean | null;
    github?: string | null;
    twitter?: string | null;
    linkedin?: string | null;
  };
  settings?: {
    /**
     * Sticky navigation (följer med vid scroll)
     */
    sticky?: boolean | null;
    /**
     * Transparent bakgrund (tills användaren scrollar)
     */
    transparent?: boolean | null;
    /**
     * Visa breadcrumbs under navigationen
     */
    showBreadcrumbs?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              /**
               * Relativ URL (t.ex. /about) eller absolut (https://...)
               */
              url: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'twitter' | 'instagram' | 'linkedin' | 'github' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logo".
 */
export interface Logo {
  id: string;
  logo?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "club-arenas".
 */
export interface ClubArena {
  id: string;
  arenas?:
    | {
        name: string;
        isPrimary?: boolean | null;
        address: string;
        city: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav_select".
 */
export interface NavSelect<T extends boolean = true> {
  items?:
    | T
    | {
        type?: T;
        label?: T;
        page?: T;
        icon?: T;
        subItems?:
          | T
          | {
              label?: T;
              page?: T;
              description?: T;
              id?: T;
            };
        highlighted?: T;
        showOnMobile?: T;
        requiresAuth?: T;
        id?: T;
      };
  logo?: T;
  ctaButton?:
    | T
    | {
        enabled?: T;
        label?: T;
        link?: T;
        style?: T;
      };
  socialLinks?:
    | T
    | {
        enabled?: T;
        github?: T;
        twitter?: T;
        linkedin?: T;
      };
  settings?:
    | T
    | {
        sticky?: T;
        transparent?: T;
        showBreadcrumbs?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logo_select".
 */
export interface LogoSelect<T extends boolean = true> {
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "club-arenas_select".
 */
export interface ClubArenasSelect<T extends boolean = true> {
  arenas?:
    | T
    | {
        name?: T;
        isPrimary?: T;
        address?: T;
        city?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}